import type { PatternDefinition } from '@/types/pattern'
import tsExample from './example.ts?raw'
import csExample from './example.cs?raw'
import pyExample from './example.py?raw'
import goExample from './example.go?raw'
import { CompositeVisualization } from './Visualization'

export const pattern: PatternDefinition = {
  slug: 'composite',
  name: 'Composite',
  category: 'structural',
  order: 5,
  summary: 'Compose objects into trees, then treat a single leaf and an entire subtree the same way.',
  intent:
    'Arrange objects in a tree so that a single item and a whole group of items can be used through the same interface.',
  problem:
    'A file system (or a UI menu, or an org chart) mixes single items with groups of items, and a group can contain more groups, nested to any depth. Code that has to ask "is this one file or a whole folder?" at every call site fills up with type checks. It breaks as soon as another level of nesting appears.',
  solution:
    'Give leaves and containers the same interface, with one operation such as getSize(). A Leaf implements it directly and returns its own value. A Composite implements the same method by looping over its children, asking each one, and combining the answers. The client calls that one method on that one interface, whether it holds a single file or a whole directory tree. The recursion is hidden inside the composites.',
  analogy:
    'Picture an org chart. Ask "what is this team\'s headcount?" and it works the same for everyone. An individual contributor answers 1. A manager asks each direct report the same question and adds up the answers, and some of those reports are managers who ask the people below them.',
  whenToUse: [
    'You need to represent part-whole hierarchies of objects as a tree.',
    'You want client code to treat single objects and groups of them the same way.',
    'The structure can nest to an arbitrary, unknown depth.',
  ],
  pros: [
    'Client code stays simple: one interface and no `if (isLeaf) … else …` branching.',
    'Open/Closed: new kinds of leaves or composites fit in without touching existing code.',
    'Building and walking arbitrarily deep, recursive structures becomes easy.',
  ],
  cons: [
    'The design can become too general, and it is hard to restrict what a composite may contain.',
    'Operations that only make sense on containers (add or remove a child) are awkward or unsafe on leaves if you put them on the shared interface.',
    'Very deep trees mean a recursive call chain all the way down, which costs stack frames and time.',
  ],
  realWorld: [
    'File systems, where directories and files share one interface (size, delete, search and so on)',
    'The DOM tree, where every Node (element or text) shares the same interface for appendChild and traversal',
    'GUI menus, where a menu holds menu items and other submenus behind the same interface',
    'Bill-of-materials and org-chart trees that total cost or headcount recursively',
  ],
  related: ['decorator', 'iterator', 'visitor', 'interpreter', 'flyweight'],
  participants: [
    {
      id: 'component',
      label: 'FileSystemItem',
      role: 'Component interface',
      kind: 'interface',
      x: 400,
      y: 50,
      width: 180,
      description: 'Declares the single getSize() operation. Every leaf and every composite implements it, so callers never need to know which kind they are holding.',
    },
    {
      id: 'client',
      label: 'Client',
      role: 'Client',
      kind: 'client',
      x: 690,
      y: 150,
      description: 'Holds a reference typed only as FileSystemItem and calls getSize() on it once — it has no idea whether that hits one file or an entire tree.',
    },
    {
      id: 'root',
      label: 'root/',
      role: 'Composite',
      kind: 'class',
      x: 400,
      y: 170,
      description: 'The top-level folder. Implements getSize() by summing the size of every child it directly holds: the docs/ folder and readme.md.',
    },
    {
      id: 'docs',
      label: 'docs/',
      role: 'Composite',
      kind: 'class',
      x: 270,
      y: 290,
      description: 'A folder nested inside root/. It is itself a composite — it holds its own children (photo.jpg and logo.png) and sums their sizes the same way root/ does.',
    },
    {
      id: 'readme',
      label: 'readme.md',
      role: 'Leaf',
      kind: 'class',
      x: 540,
      y: 290,
      description: 'A plain file directly inside root/. As a leaf it has no children — getSize() just returns its own stored size immediately.',
    },
    {
      id: 'photo',
      label: 'photo.jpg',
      role: 'Leaf',
      kind: 'class',
      x: 185,
      y: 400,
      description: 'A file inside docs/. A leaf with no children of its own — getSize() returns its own size directly.',
    },
    {
      id: 'logo',
      label: 'logo.png',
      role: 'Leaf',
      kind: 'class',
      x: 365,
      y: 400,
      description: 'A second file inside docs/, sitting alongside photo.jpg. Also a leaf — it returns its own size with no further recursion.',
    },
  ],
  relations: [
    {
      id: 'call',
      from: 'client',
      to: 'root',
      type: 'calls',
      label: 'getSize()',
      description: 'The client calls getSize() exactly once, on the root item — the same call it would make on a single, standalone file.',
      code: 'usage',
    },
    {
      id: 'rootImpl',
      from: 'root',
      to: 'component',
      type: 'implements',
      description: 'root/ implements FileSystemItem like everything else in the tree.',
      code: 'folder',
    },
    {
      id: 'readmeImpl',
      from: 'readme',
      to: 'component',
      type: 'implements',
      description: 'readme.md implements the very same FileSystemItem interface, even though it is a leaf with no children.',
      bend: 70,
      code: 'file',
    },
    {
      id: 'rootDocs',
      from: 'root',
      to: 'docs',
      type: 'holds',
      label: 'children[]',
      description: 'root/ holds a reference to docs/ in its children array — this is the structural containment edge the recursion walks down.',
      code: 'build',
    },
    {
      id: 'rootReadme',
      from: 'root',
      to: 'readme',
      type: 'holds',
      label: 'children[]',
      description: 'root/ also directly holds readme.md as a child, alongside the docs/ folder.',
      code: 'build',
    },
    {
      id: 'docsPhoto',
      from: 'docs',
      to: 'photo',
      type: 'holds',
      label: 'children[]',
      description: 'docs/ holds photo.jpg as one of its own children.',
      code: 'build',
    },
    {
      id: 'docsLogo',
      from: 'docs',
      to: 'logo',
      type: 'holds',
      label: 'children[]',
      description: 'docs/ holds logo.png as its other child, completing the tree.',
      code: 'build',
    },
  ],
  steps: [
    {
      title: 'Build the tree',
      description: 'root/ holds docs/ and readme.md as direct children. docs/ in turn holds photo.jpg and logo.png — a tree, nested two levels deep.',
      highlight: ['root', 'rootDocs', 'docs', 'rootReadme', 'readme', 'docsPhoto', 'photo', 'docsLogo', 'logo'],
      notes: { root: 'children: 2', docs: 'children: 2' },
      code: 'build',
    },
    {
      title: 'Client calls getSize()',
      description: 'The client calls getSize() once, on root/ — the exact same call it would make if root/ were a single file instead of a whole tree.',
      highlight: ['client', 'call', 'root'],
      packets: [{ relation: 'call', label: 'getSize()' }],
      code: 'usage',
    },
    {
      title: 'root/ asks its first child, docs/',
      description: 'root/ does not know how to measure itself directly — it loops over its children in order and calls getSize() on the first one, docs/, waiting for that whole subtree to resolve before it moves on to readme.md.',
      highlight: ['root', 'rootDocs', 'docs'],
      packets: [{ relation: 'rootDocs', label: 'getSize()' }],
      code: 'folder',
    },
    {
      title: 'docs/ ripples the call further down',
      description: 'docs/ is itself a composite, so it runs the exact same logic as root/: it calls getSize() on each of its own children, photo.jpg and logo.png.',
      highlight: ['docs', 'docsPhoto', 'photo', 'docsLogo', 'logo'],
      packets: [
        { relation: 'docsPhoto', label: 'getSize()' },
        { relation: 'docsLogo', label: 'getSize()' },
      ],
      code: 'folder',
    },
    {
      title: 'Leaves hit bottom and answer immediately',
      description: 'photo.jpg and logo.png have no children to delegate to — each one just returns its own stored size, right away. readme.md has not even been asked yet.',
      highlight: ['photo', 'docsPhoto', 'logo', 'docsLogo'],
      packets: [
        { relation: 'docsPhoto', label: '2400 KB', reverse: true },
        { relation: 'docsLogo', label: '800 KB', reverse: true },
      ],
      notes: { photo: '2400 KB', logo: '800 KB' },
      code: 'file',
    },
    {
      title: 'docs/ totals its children and bubbles up',
      description: 'docs/ adds 2400 KB + 800 KB from its two children and returns that 3200 KB subtotal back up to root/. Only now, with that whole subtree resolved, does root/ move on.',
      highlight: ['docs', 'rootDocs', 'root'],
      packets: [{ relation: 'rootDocs', label: '3200 KB', reverse: true }],
      notes: { docs: '3200 KB' },
      code: 'folder',
    },
    {
      title: 'root/ asks its next child, readme.md',
      description: 'With the docs/ subtotal in hand, root/ moves to the next entry in its children array and calls getSize() on readme.md.',
      highlight: ['root', 'rootReadme', 'readme'],
      packets: [{ relation: 'rootReadme', label: 'getSize()' }],
      code: 'folder',
    },
    {
      title: 'readme.md answers immediately',
      description: 'readme.md has no children either — it returns its own stored size straight away.',
      highlight: ['readme', 'rootReadme'],
      packets: [{ relation: 'rootReadme', label: '1100 KB', reverse: true }],
      notes: { readme: '1100 KB' },
      code: 'file',
    },
    {
      title: 'root/ totals everything and returns to the client',
      description: 'root/ adds the 3200 KB subtotal from docs/ to readme.md’s 1100 KB, for a grand total of 4300 KB, and returns that single number to the client.',
      highlight: ['root', 'call', 'client'],
      packets: [{ relation: 'call', label: '4300 KB', reverse: true }],
      notes: { root: '4300 KB' },
      code: 'folder',
    },
    {
      title: 'One call, whole tree measured',
      description: 'The client made a single getSize() call and got back the total size of an entire nested tree — it never had to know how deep that tree went.',
      highlight: ['client'],
      notes: { client: 'total: 4300 KB' },
      code: 'usage',
    },
  ],
  code: tsExample,
  csharp: csExample,
  python: pyExample,
  go: goExample,
  Visualization: CompositeVisualization,
}
