import type { ArchitectureDefinition } from '@/types/architecture'
import tsExample from './example.ts?raw'
import csExample from './example.cs?raw'
import pyExample from './example.py?raw'
import goExample from './example.go?raw'
import { VerticalSliceVisualization } from './Visualization'

export const architecture: ArchitectureDefinition = {
  slug: 'vertical-slice',
  name: 'Vertical Slice Architecture',
  paradigm: 'oo',
  order: 8,
  summary: 'Cut the codebase by feature instead of by technical layer, so each request owns its handler and data access end to end.',
  intent:
    'Organize code around individual requests — one command or query, its handler, and its own data access — instead of around shared technical layers, so a feature can be understood, tested and changed by looking in one place.',
  problem:
    'A layered architecture shares a service layer and a repository layer across every feature. As the number of features grows, those shared layers accumulate methods that only one feature needs, a change made for one feature risks breaking another that happens to share the same class, and a trivial feature still has to pass through every layer a complex one needs.',
  solution:
    'Instead of one shared stack, cut the system into slices: PlaceOrder and GetOrder each get their own request type, their own handler, their own data-access code and their own validator, with nothing shared between them except cross-cutting infrastructure. A small Mediator routes each request to the one handler registered for it, through a pipeline of behaviours — logging, validation — that wrap every handler the same way. ValidationBehaviour holds no knowledge of PlaceOrder or GetOrder itself: each slice registers its own validator against the behaviour, keyed by its request type, so cross-cutting concerns do not have to be reimplemented inside each slice and the behaviour never has to change when a slice is added.',
  analogy:
    'A food court instead of a single kitchen with stations. A layered kitchen has one prep station, one grill and one plating counter that every dish passes through in the same order. A food court gives each vendor — tacos, sushi, noodles — its own self-contained stall with its own prep and its own counter; a shared order board (the mediator) just tells a customer which stall to walk up to.',
  whenToUse: [
    'A codebase has accumulated "shared" service and repository classes that only one feature actually uses, so every change ripples sideways into unrelated features.',
    'Features vary enormously in complexity, and a one-size-fits-all layered stack forces a trivial feature through just as much ceremony as a complex one.',
    'Teams are organized around features rather than technical layers, and want their code structure to match.',
    'A command/query split is wanted but standing up a fully separate read and write store (CQRS) is overkill for most endpoints.',
  ],
  pros: [
    'A feature can be understood, tested and deleted by looking at one slice, instead of hunting across shared layers.',
    'Two slices can use completely different internal shapes — one simple CRUD, one with a rich domain model — without forcing the other to match.',
    'New features add a new slice instead of touching shared service and repository classes, lowering the chance of breaking something unrelated.',
    'The pipeline still gives every slice the same cross-cutting behaviour (logging, validation) without a shared base class each handler must inherit from, and without the shared infrastructure ever naming a specific slice.',
  ],
  cons: [
    'Code that really is common to several slices (the same validation rule, the same formatting) can end up duplicated instead of shared.',
    'Without an agreed convention for what a slice contains, different developers can structure their slices differently, and the codebase loses one predictable shape.',
    'Still needs a pipeline or similar convention for cross-cutting concerns, or every handler ends up reimplementing logging and validation by hand.',
    'Small, closely related features can fragment into many near-duplicate slices when a smaller shared layer would have been simpler.',
  ],
  realWorld: [
    'MediatR-based .NET APIs organized as Features/PlaceOrder, Features/GetOrder folders, each with its own Command or Query, Handler and validator',
    'FastEndpoints and similar .NET libraries that pair one endpoint with one request, one response and one handler file',
    "Jimmy Bogard's \"Vertical Slice Architecture\" talks and blog posts, which popularized the term",
    'Serverless functions-per-endpoint designs, where each function is effectively its own slice with its own data access',
  ],
  concepts: [
    { term: 'Slice', description: 'One vertical cut of the system — one request type, its handler, and its own data access — built, tested and changed independently of other slices.' },
    { term: 'Request', description: 'A command (PlaceOrder) or query (GetOrder) sent through the mediator. Each request type has exactly one handler.' },
    { term: 'Handler', description: 'The one class that knows how to carry out a single request. It lives inside its slice; nothing outside the slice calls it directly.' },
    { term: 'Mediator', description: "Looks up the handler registered for a request's type and routes the request to it, so callers never hold a reference to a concrete handler." },
    { term: 'Pipeline behaviour', description: 'Cross-cutting code (logging, validation) that wraps every handler the mediator dispatches to, without any handler knowing it is there. ValidationBehaviour stays generic by holding a registry of per-slice validators instead of naming any request type itself.' },
    { term: 'Feature folder', description: "The physical layout that often accompanies this architecture: one folder per slice holding that slice's request, handler and data access together, instead of spreading them across layer folders." },
  ],
  variants: [
    { name: 'Feature folders in a layered codebase', description: "Keep the overall layered structure, but group a feature's controller, service and repository into one folder instead of three — a lightweight first step toward full vertical slices." },
    { name: 'Slices with a shared domain model', description: 'Multiple slices call into the same domain or aggregate types instead of each slice owning its own, trading some independence for less duplication.' },
    { name: 'Fully independent slices', description: 'Each slice owns its own request, handler and data access end to end, even if that means two slices duplicate similar-looking code — independence is the point.' },
  ],

  commonlyUsedWith: {
    designPatterns: [
      { slug: 'mediator', why: 'Every request — PlaceOrder or GetOrder — is sent to the Mediator, which looks up the one registered handler and routes the request there, so callers never reference a handler directly.' },
      { slug: 'command', why: 'PlaceOrder is a plain command object (type, orderId, customerId, totalCents) describing an intent, handled by exactly one handler — the Command pattern.' },
      { slug: 'chain-of-responsibility', why: "LoggingBehaviour and ValidationBehaviour each receive a next() and decide whether to call it; ValidationBehaviour not calling next() is exactly a chain link short-circuiting the rest of the chain." },
      { slug: 'decorator', why: 'The same LoggingBehaviour and ValidationBehaviour also wrap every handler with extra behaviour (logging, validating) while the handler keeps the same interface and never knows it is wrapped — the Decorator half of the same pipeline.' },
      { slug: 'repository', why: 'PlaceOrderStore and GetOrderStore are each a slice-local repository over the shared OrdersTable, so handlers never touch the table directly.' },
    ],
    architectures: [
      { slug: 'layered', why: 'Vertical Slice is the direct alternative: it cuts the system by feature (PlaceOrder, GetOrder) instead of by technical layer (presentation, application, data access).' },
      { slug: 'cqrs', why: 'The two slices already split naturally into a command (PlaceOrder) and a query (GetOrder), the same split CQRS makes explicit at the architecture level.' },
      { slug: 'ddd', why: 'A slice can sit on top of a shared domain model for its invariants, or — as in this example — skip one entirely and talk straight to its own data access for a simple feature.' },
    ],
  },

  // Diagram (viewBox 800 × 480, x/y are box centres)
  viewBox: '0 0 800 480',
  participants: [
    {
      id: 'client',
      label: 'Client',
      role: 'Client',
      kind: 'client',
      x: 400,
      y: 40,
      description: 'Sends a PlaceOrder command and a GetOrder query, both through the same mediator. It never references PlaceOrderHandler or GetOrderHandler directly.',
    },
    {
      id: 'mediator',
      label: 'Mediator',
      role: 'Request routing',
      kind: 'class',
      x: 400,
      y: 120,
      width: 170,
      description: "Looks up the one handler registered for a request's type and sends the request through the pipeline to reach it.",
      patterns: ['mediator'],
    },
    {
      id: 'loggingBehaviour',
      label: 'LoggingBehaviour',
      role: 'Pipeline behaviour',
      kind: 'class',
      x: 400,
      y: 200,
      width: 190,
      description: 'Logs before and after every request, then calls next() to let the rest of the pipeline run. Wraps every slice the same way.',
      patterns: ['chain-of-responsibility', 'decorator'],
    },
    {
      id: 'validationBehaviour',
      label: 'ValidationBehaviour',
      role: 'Pipeline behaviour',
      kind: 'class',
      x: 400,
      y: 280,
      width: 200,
      description: "Looks up the validator the incoming request's slice registered for its type and runs it, if one was registered. If that validator rejects the request, ValidationBehaviour never calls next() — the handler simply never runs. It holds no knowledge of PlaceOrder or GetOrder itself.",
      patterns: ['chain-of-responsibility', 'decorator'],
    },
    {
      id: 'placeOrderHandler',
      label: 'PlaceOrderHandler',
      role: 'PlaceOrder slice: handler',
      kind: 'class',
      x: 190,
      y: 280,
      width: 190,
      description: 'The only class that knows how to carry out PlaceOrder. Builds the row and asks its own store to save it.',
      patterns: ['command'],
    },
    {
      id: 'placeOrderStore',
      label: 'PlaceOrderStore',
      role: 'PlaceOrder slice: data access',
      kind: 'class',
      x: 190,
      y: 390,
      width: 190,
      description: "This slice's own narrow data-access class. Nothing outside the PlaceOrder slice calls it.",
      patterns: ['repository'],
    },
    {
      id: 'getOrderHandler',
      label: 'GetOrderHandler',
      role: 'GetOrder slice: handler',
      kind: 'class',
      x: 610,
      y: 280,
      width: 190,
      description: 'The only class that knows how to carry out GetOrder. Shares no code with PlaceOrderHandler.',
    },
    {
      id: 'getOrderStore',
      label: 'GetOrderStore',
      role: 'GetOrder slice: data access',
      kind: 'class',
      x: 610,
      y: 390,
      width: 190,
      description: "This slice's own narrow data-access class, reading from the same table PlaceOrderStore writes to.",
      patterns: ['repository'],
    },
  ],
  relations: [
    {
      id: 'send',
      from: 'client',
      to: 'mediator',
      type: 'calls',
      label: 'send(PlaceOrder)',
      description: 'The client builds a PlaceOrder command and hands it to the mediator — it has no reference to PlaceOrderHandler.',
      code: 'usage',
    },
    {
      id: 'dispatchToLogging',
      from: 'mediator',
      to: 'loggingBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: "The mediator has wrapped the handler in every registered behaviour; LoggingBehaviour, registered first, is the outermost.",
      code: 'mediator',
    },
    {
      id: 'dispatchToValidation',
      from: 'loggingBehaviour',
      to: 'validationBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: 'Having logged the start of the request, LoggingBehaviour calls next() to pass it to ValidationBehaviour.',
      code: 'loggingBehaviour',
    },
    {
      id: 'dispatchToHandler',
      from: 'validationBehaviour',
      to: 'placeOrderHandler',
      type: 'calls',
      label: 'next(request)',
      description: 'The totalCents is positive, so ValidationBehaviour calls next(), finally reaching PlaceOrderHandler.',
      code: 'validationBehaviour',
    },
    {
      id: 'persist',
      from: 'placeOrderHandler',
      to: 'placeOrderStore',
      type: 'calls',
      label: 'save(row)',
      description: 'The handler asks its own slice-local store to persist the order into the shared table.',
      code: 'placeOrderHandler',
    },
    {
      id: 'sendQuery',
      from: 'client',
      to: 'mediator',
      type: 'calls',
      label: 'send(GetOrder)',
      description: 'A moment later, the client sends a completely different request type through the very same mediator.',
      code: 'usage',
    },
    {
      id: 'queryToLogging',
      from: 'mediator',
      to: 'loggingBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: 'GetOrder goes through the identical pipeline as PlaceOrder did — the same LoggingBehaviour instance, unaware which slice it is wrapping.',
      bend: 40,
      code: 'mediator',
    },
    {
      id: 'queryToValidation',
      from: 'loggingBehaviour',
      to: 'validationBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: 'LoggingBehaviour logs the start of GetOrder, then calls next() just as it did for PlaceOrder.',
      bend: 40,
      code: 'loggingBehaviour',
    },
    {
      id: 'queryToHandler',
      from: 'validationBehaviour',
      to: 'getOrderHandler',
      type: 'calls',
      label: 'next(request)',
      description: "ValidationBehaviour runs the GetOrder slice's own validator; the orderId is present, so it calls next(), reaching GetOrderHandler.",
      code: 'validationBehaviour',
    },
    {
      id: 'read',
      from: 'getOrderHandler',
      to: 'getOrderStore',
      type: 'calls',
      label: 'findById(orderId)',
      description: "The query handler reads through its own slice-local store — it never touches PlaceOrderStore or PlaceOrderHandler.",
      code: 'getOrderHandler',
    },
    {
      id: 'sendInvalid',
      from: 'client',
      to: 'mediator',
      type: 'calls',
      label: 'send(PlaceOrder totalCents: 0)',
      description: 'A second PlaceOrder, this time invalid, goes through the identical pipeline as the first one.',
      bend: -40,
      code: 'usage',
    },
    {
      id: 'invalidToLogging',
      from: 'mediator',
      to: 'loggingBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: 'LoggingBehaviour runs first regardless of what the request contains, so it logs "handling" before anything has checked whether the request is valid.',
      bend: -40,
      code: 'mediator',
    },
    {
      id: 'invalidToValidation',
      from: 'loggingBehaviour',
      to: 'validationBehaviour',
      type: 'calls',
      label: 'next(request)',
      description: 'LoggingBehaviour calls next() as usual — it has no idea the request is about to be rejected.',
      bend: -40,
      code: 'loggingBehaviour',
    },
  ],

  // Animated scenario
  steps: [
    {
      title: 'Cut by feature, not by layer',
      description:
        'PlaceOrder and GetOrder are each a self-contained slice: their own request, their own handler, their own data access. A shared Mediator and a pipeline of behaviours are the only things that cross slice boundaries.',
      highlight: ['client', 'mediator', 'loggingBehaviour', 'validationBehaviour', 'placeOrderHandler', 'placeOrderStore', 'getOrderHandler', 'getOrderStore'],
    },
    {
      title: 'Client sends the PlaceOrder command',
      description: 'The client builds a PlaceOrder command and hands it to the Mediator. It never references PlaceOrderHandler directly.',
      highlight: ['client', 'send', 'mediator'],
      packets: [{ relation: 'send', label: 'PlaceOrder' }],
      notes: { mediator: 'routing' },
      code: 'usage',
    },
    {
      title: 'The pipeline logs the request',
      description: 'The mediator has wrapped the handler in every registered behaviour. LoggingBehaviour, registered first, runs first: it logs, then calls next().',
      highlight: ['mediator', 'dispatchToLogging', 'loggingBehaviour'],
      packets: [{ relation: 'dispatchToLogging', label: 'next(request)' }],
      notes: { loggingBehaviour: 'LOG: handling PlaceOrder' },
      code: 'loggingBehaviour',
    },
    {
      title: 'The pipeline validates the request',
      description: "ValidationBehaviour runs the PlaceOrder slice's own validator. totalCents is 2500, which is positive, so the validator passes and ValidationBehaviour calls next(), continuing the chain.",
      highlight: ['loggingBehaviour', 'dispatchToValidation', 'validationBehaviour'],
      packets: [{ relation: 'dispatchToValidation', label: 'next(request)' }],
      notes: { validationBehaviour: 'valid' },
      code: 'validationBehaviour',
    },
    {
      title: 'The handler saves through its own store',
      description: 'PlaceOrderHandler finally runs, builds the row, and saves it through PlaceOrderStore — this slice\'s own data access, never touched by GetOrder.',
      highlight: ['validationBehaviour', 'dispatchToHandler', 'placeOrderHandler', 'persist', 'placeOrderStore'],
      packets: [
        { relation: 'dispatchToHandler', label: 'next(request)' },
        { relation: 'persist', label: 'save(row)', after: 0 },
      ],
      notes: { placeOrderStore: 'order-7 saved' },
      code: 'placeOrderHandler',
    },
    {
      title: 'Client sends the GetOrder query through the same pipeline',
      description: 'The client now sends a GetOrder query — a different request type — through the exact same Mediator, LoggingBehaviour and ValidationBehaviour instances.',
      highlight: ['client', 'sendQuery', 'mediator', 'queryToLogging', 'loggingBehaviour', 'queryToValidation', 'validationBehaviour'],
      packets: [
        { relation: 'sendQuery', label: 'GetOrder' },
        { relation: 'queryToLogging', label: 'next(request)', after: 0 },
        { relation: 'queryToValidation', label: 'next(request)', after: 1 },
      ],
      notes: { loggingBehaviour: 'LOG: handling GetOrder', validationBehaviour: 'valid' },
      code: 'usage',
    },
    {
      title: "The query handler reads from its own slice's store",
      description: "GetOrderHandler runs and reads through GetOrderStore — its own data access over the same shared table PlaceOrderStore wrote to.",
      highlight: ['validationBehaviour', 'queryToHandler', 'getOrderHandler', 'read', 'getOrderStore'],
      packets: [
        { relation: 'queryToHandler', label: 'next(request)' },
        { relation: 'read', label: 'findById(orderId)', after: 0 },
      ],
      notes: { getOrderStore: 'order-7 found' },
      code: 'getOrderHandler',
    },
    {
      title: 'An invalid PlaceOrder is short-circuited',
      description:
        'The client sends a second PlaceOrder, this time with totalCents: 0. LoggingBehaviour runs before ValidationBehaviour in this pipeline, so it still logs "handling" — logging order does not depend on whether the request turns out to be valid. ValidationBehaviour then rejects it and never calls next(): PlaceOrderHandler never runs, nothing is saved, and LoggingBehaviour\'s "handled" log never prints either, because the exception propagates straight back through it.',
      highlight: ['client', 'sendInvalid', 'mediator', 'invalidToLogging', 'loggingBehaviour', 'invalidToValidation', 'validationBehaviour'],
      packets: [
        { relation: 'sendInvalid', label: 'PlaceOrder (totalCents: 0)' },
        { relation: 'invalidToLogging', label: 'next(request)', after: 0 },
        { relation: 'invalidToValidation', label: 'next(request)', after: 1 },
      ],
      notes: { loggingBehaviour: 'LOG: handling PlaceOrder (no "handled")', validationBehaviour: 'rejected: positive totalCents required' },
      code: 'usage',
    },
  ],

  code: tsExample,
  csharp: csExample,
  python: pyExample,
  go: goExample,
  Visualization: VerticalSliceVisualization,
}
