import type { PatternDefinition } from '@/types/pattern'
import tsExample from './example.ts?raw'
import csExample from './example.cs?raw'
import pyExample from './example.py?raw'
import { DependencyInjectionVisualization } from './Visualization'

export const pattern: PatternDefinition = {
  slug: 'dependency-injection',
  name: 'Dependency Injection',
  category: 'enterprise',
  order: 1,
  summary: 'Hand objects their dependencies from the outside instead of letting them construct their own.',
  intent: 'Give an object the collaborators it needs from the outside, instead of letting it create them itself.',
  problem: "OrderService needs a database repository and a way to send email. If it calls new SqlOrderRepository() and new SmtpEmailSender() itself, it is hard-wired to those concrete classes, and to whatever they need in turn. Testing OrderService then means testing the real repository and the real mailer too. Swapping either one means editing OrderService's source.",
  solution: 'Each class lists what it needs as constructor parameters, typed as interfaces where it matters, and never creates those dependencies itself. A container (or just a few lines of composition code) builds the dependency graph from the bottom up, leaves first, and passes each finished instance to the constructor of whatever needs it, until the object the application actually wants is fully wired.',
  analogy: 'A car factory does not make the engine build its own pistons. Pistons, engine and chassis are built separately and assembled in order, and each station is handed exactly the finished parts it needs.',
  whenToUse: [
    "A class's dependencies have dependencies of their own, and wiring them by hand is repetitive or error-prone.",
    'You want to swap in a fake or mock implementation in tests without touching the class under test.',
    'Different environments (dev, test, prod) need different concrete implementations behind the same interface.',
    'You want construction logic in one place instead of scattered across every class that happens to need an object.',
  ],
  pros: [
    'Classes depend on abstractions, not concrete classes, so implementations are easy to swap.',
    'Testing is easy: give the class under test a fake or mock instead of the real dependency.',
    'Construction logic lives in one place instead of being repeated in every consumer.',
  ],
  cons: [
    'Adds indirection: instead of following a chain of `new` calls, you now follow a container.',
    'Wiring mistakes (a missing registration, a lifetime mismatch) show up when something is resolved, not at compile time.',
    'Overkill for small scripts with only one or two simple dependencies.',
    'Passing the container itself into a class so it can call resolve() whenever it needs something is Service Locator, not Dependency Injection. It hides the dependency instead of declaring it.',
  ],
  realWorld: [
    'Angular and NestJS: constructor injection driven by decorators (@Injectable, @Inject)',
    'Spring Framework (Java): the ApplicationContext as the container',
    'ASP.NET Core: IServiceCollection / IServiceProvider built into the framework',
    'InversifyJS and tsyringe: lightweight containers for plain TypeScript/Node apps',
  ],
  related: ['singleton', 'factory-method', 'strategy', 'repository'],

  participants: [
    {
      id: 'container',
      label: 'Container',
      role: 'DI Container / Injector',
      kind: 'client',
      x: 110,
      y: 230,
      description:
        'Builds and wires every object in the graph at startup, leaves first. Nothing else in the app calls new on a dependency — only the container does. The startup code that configures and invokes it (see the usage snippet) is the real Composition Root.',
    },
    {
      id: 'orderController',
      label: 'OrderController',
      role: 'Root of the graph',
      kind: 'class',
      x: 430,
      y: 70,
      width: 170,
      description:
        'The object the application actually wants. Resolving it forces the container to build its entire dependency chain first.',
    },
    {
      id: 'orderService',
      label: 'OrderService',
      role: 'Service',
      kind: 'class',
      x: 430,
      y: 190,
      description:
        'Coordinates placing an order. Depends on OrderRepository and EmailSender, both received as constructor parameters instead of being constructed internally.',
    },
    {
      id: 'orderRepository',
      label: 'OrderRepository',
      role: 'Abstraction',
      kind: 'interface',
      x: 230,
      y: 300,
      width: 170,
      description: 'Declares save() and findById(). OrderService depends only on this interface, never on a concrete storage mechanism.',
    },
    {
      id: 'emailSender',
      label: 'EmailSender',
      role: 'Abstraction',
      kind: 'interface',
      x: 630,
      y: 300,
      description: 'Declares send(). OrderService depends only on this interface, never on a concrete mailer.',
    },
    {
      id: 'config',
      label: 'Config',
      role: 'Leaf dependency',
      kind: 'class',
      x: 230,
      y: 400,
      description: 'Holds configuration values such as connection strings. Has no dependencies of its own, so the container can build it first.',
    },
    {
      id: 'smtpEmailSender',
      label: 'SmtpEmailSender',
      role: 'Concrete implementation',
      kind: 'class',
      x: 630,
      y: 400,
      width: 170,
      description: 'Sends real email over SMTP — one of possibly several implementations of EmailSender the container could hand out.',
    },
    {
      id: 'sqlOrderRepository',
      label: 'SqlOrderRepository',
      role: 'Concrete implementation',
      kind: 'class',
      x: 110,
      y: 400,
      width: 170,
      description: 'Persists orders to SQL. Needs a Config, injected through its constructor rather than constructed internally — one of possibly several implementations of OrderRepository the container could hand out.',
    },
  ],

  relations: [
    {
      id: 'create-config',
      from: 'container',
      to: 'config',
      type: 'creates',
      label: 'new Config()',
      description: 'The container builds Config first — it has no dependencies of its own, so it can be the very first thing constructed.',
      code: 'config',
      bend: -10,
    },
    {
      id: 'create-repo',
      from: 'container',
      to: 'sqlOrderRepository',
      type: 'creates',
      label: 'new SqlOrderRepository()',
      description: 'Once Config exists, the container builds SqlOrderRepository and passes the Config instance straight into its constructor.',
      code: 'sqlOrderRepository',
      bend: 20,
    },
    {
      id: 'create-email',
      from: 'container',
      to: 'smtpEmailSender',
      type: 'creates',
      label: 'new SmtpEmailSender()',
      description: 'SmtpEmailSender is also a leaf, so the container can build it independently of the repository branch.',
      code: 'smtpEmailSender',
      bend: -30,
    },
    {
      id: 'create-service',
      from: 'container',
      to: 'orderService',
      type: 'creates',
      label: 'new OrderService(repo, email)',
      description: 'With both of its dependencies built, OrderService can now be constructed and wired to them.',
      code: 'orderService',
      bend: 35,
    },
    {
      id: 'create-controller',
      from: 'container',
      to: 'orderController',
      type: 'creates',
      label: 'new OrderController(service)',
      description: 'OrderController is built last, once everything beneath it already exists.',
      code: 'orderController',
      bend: -45,
    },
    {
      id: 'repo-holds-config',
      from: 'sqlOrderRepository',
      to: 'config',
      type: 'holds',
      label: 'config',
      description: 'SqlOrderRepository stores the Config instance it was handed; it never constructs one itself.',
      code: 'sqlOrderRepository',
    },
    {
      id: 'email-implements',
      from: 'smtpEmailSender',
      to: 'emailSender',
      type: 'implements',
      description: 'SmtpEmailSender implements the EmailSender interface — the only thing OrderService is allowed to know about it.',
    },
    {
      id: 'repo-implements',
      from: 'sqlOrderRepository',
      to: 'orderRepository',
      type: 'implements',
      description: 'SqlOrderRepository implements the OrderRepository interface — the only thing OrderService is allowed to know about it.',
      bend: 15,
    },
    {
      id: 'service-holds-repo',
      from: 'orderService',
      to: 'orderRepository',
      type: 'holds',
      label: 'repository',
      description: 'OrderService stores its repository only as OrderRepository — it has no idea SqlOrderRepository (or a fake) is behind it.',
      code: 'orderService',
      bend: 15,
    },
    {
      id: 'service-holds-email',
      from: 'orderService',
      to: 'emailSender',
      type: 'holds',
      label: 'emailSender',
      description: 'OrderService stores its mailer only as EmailSender — it has no idea SmtpEmailSender (or a fake) is behind it.',
      code: 'orderService',
      bend: -15,
    },
    {
      id: 'controller-holds-service',
      from: 'orderController',
      to: 'orderService',
      type: 'holds',
      label: 'service',
      description: 'OrderController stores the OrderService instance it was constructed with.',
      code: 'orderController',
    },
    {
      id: 'client-call',
      from: 'container',
      to: 'orderController',
      type: 'calls',
      label: 'handle()',
      description: 'Shown from the container for proximity, but it is application code — not the container — that calls handle() on the resolved OrderController, exactly like any other object. DI only changes how it was built, not how it is used.',
      code: 'usage',
      bend: -60,
    },
  ],

  steps: [
    {
      title: 'Resolve OrderController',
      description:
        'The app asks the container to resolve OrderController. The container looks up the provider registered for it, sees it needs an OrderService, and must build that first — and recursively, whatever OrderService needs.',
      highlight: ['container', 'orderController'],
      notes: { container: 'resolving OrderController' },
      code: 'container',
    },
    {
      title: 'Build the first leaf: Config',
      description: 'Config has no constructor dependencies, so the container builds it immediately and caches the instance.',
      highlight: ['container', 'create-config', 'config'],
      packets: [{ relation: 'create-config', label: 'new Config()' }],
      notes: { config: 'built ✓' },
      code: 'config',
    },
    {
      title: 'SqlOrderRepository is wired to it',
      description: 'The container builds SqlOrderRepository next — the registered implementation of OrderRepository — and the Config instance built a moment ago flies straight into its constructor slot.',
      highlight: ['create-repo', 'repo-holds-config', 'repo-implements', 'sqlOrderRepository', 'orderRepository'],
      packets: [
        { relation: 'create-repo', label: 'new SqlOrderRepository()' },
        { relation: 'repo-holds-config', label: 'config', reverse: true, after: 0 },
      ],
      notes: { config: 'built ✓', sqlOrderRepository: 'built ✓' },
      code: 'sqlOrderRepository',
    },
    {
      title: 'The other branch: SmtpEmailSender',
      description:
        'SmtpEmailSender is also a leaf. The container builds it independently of the repository branch — order between independent branches does not matter, only dependency order does.',
      highlight: ['create-email', 'email-implements', 'smtpEmailSender'],
      packets: [{ relation: 'create-email', label: 'new SmtpEmailSender()' }],
      notes: { config: 'built ✓', sqlOrderRepository: 'built ✓', smtpEmailSender: 'built ✓' },
      code: 'smtpEmailSender',
    },
    {
      title: 'OrderService receives both dependencies',
      description: 'Only now that an OrderRepository and an EmailSender exist can OrderService be constructed. Both instances fly into its constructor at once, each typed as the interface.',
      highlight: ['create-service', 'service-holds-repo', 'service-holds-email', 'orderService'],
      packets: [
        { relation: 'create-service', label: 'new OrderService()' },
        { relation: 'service-holds-repo', label: 'repository', reverse: true, after: 0 },
        { relation: 'service-holds-email', label: 'emailSender', reverse: true, after: 0 },
      ],
      notes: { sqlOrderRepository: 'built ✓', smtpEmailSender: 'built ✓', orderService: 'built ✓' },
      code: 'orderService',
    },
    {
      title: 'OrderController is wired last',
      description: 'The root of the graph is built last, once the one thing it needs — OrderService — is ready. The graph is now fully wired, bottom-up.',
      highlight: ['create-controller', 'controller-holds-service', 'orderController'],
      packets: [
        { relation: 'create-controller', label: 'new OrderController()' },
        { relation: 'controller-holds-service', label: 'service', reverse: true, after: 0 },
      ],
      notes: { orderService: 'built ✓', orderController: 'built ✓' },
      code: 'orderController',
    },
    {
      title: 'Business as usual',
      description: 'The application calls handle() on the resolved OrderController exactly as it would on any hand-built object. Nothing about using it reveals that a container built it.',
      highlight: ['container', 'client-call', 'orderController'],
      packets: [{ relation: 'client-call', label: 'handle()' }],
      notes: { orderController: 'built ✓' },
      code: 'usage',
    },
    {
      title: 'Tests skip the container entirely',
      description: 'A unit test just calls new OrderService(fakeRepo, new FakeEmailSender()) directly — no container involved. OrderService never notices the difference: it only ever depended on the OrderRepository and EmailSender interfaces.',
      highlight: ['service-holds-repo', 'service-holds-email', 'orderRepository', 'emailSender'],
      notes: { orderService: 'wired by hand (test)' },
      code: 'test',
    },
  ],

  code: tsExample,
  csharp: csExample,
  python: pyExample,

  Visualization: DependencyInjectionVisualization,
}
