import type { PatternDefinition } from '@/types/pattern'
import tsExample from './example.ts?raw'
import csExample from './example.cs?raw'
import pyExample from './example.py?raw'
import goExample from './example.go?raw'

export const pattern: PatternDefinition = {
  slug: 'factory-method',
  name: 'Factory Method',
  category: 'creational',
  order: 2,
  summary: 'Let subclasses decide which concrete class to instantiate.',
  intent:
    'Let subclasses decide which concrete class to create, so the code that needs an object only depends on its interface.',
  problem:
    'A Logistics base class plans deliveries, but the vehicle it needs (truck, ship, plane) depends on the kind of logistics company. If the base class hard-codes `new Truck()`, you cannot add sea or air delivery without rewriting its planning logic.',
  solution:
    'Move the "create the vehicle" step into its own method, createTransport(), and make it abstract. Each subclass (RoadLogistics, SeaLogistics) overrides it to return the Transport it needs. The shared planning code in the base class calls createTransport() and never learns which concrete class came back.',
  analogy:
    'A logistics company always follows the same planDelivery() routine: pack, route, dispatch. But a road branch dispatches a truck and a sea branch dispatches a ship. The "which vehicle?" step is the factory method, and each branch fills it in its own way.',
  whenToUse: [
    'A class cannot know ahead of time which concrete class of object it will need to create.',
    'You want subclasses to choose the objects they create, without changing the shared code.',
    'You want subclasses, not the base class, to pick the concrete product by overriding a single creation method.',
  ],
  pros: [
    'The creator is not tightly coupled to concrete product classes.',
    'Single Responsibility: the code that creates products lives in one place.',
    'Open/Closed: add a new product type by adding a new creator subclass, without changing existing code.',
  ],
  cons: [
    'You may need a new subclass for every product variant, so the class hierarchy grows.',
    'It adds a layer of indirection, which is overkill if there will only ever be one product type.',
  ],
  realWorld: [
    "The GoF book's own example: an Application base class whose subclasses override CreateDocument() to return their own kind of Document",
    'java.util.Collection.iterator(): each concrete collection overrides it to return its own Iterator',
    'A Dialog base class whose subclasses override createButton() to return a platform-specific button',
  ],
  related: ['abstract-factory', 'prototype', 'builder', 'template-method'],
  participants: [
    {
      id: 'transport',
      label: 'Transport',
      role: 'Product interface',
      kind: 'interface',
      x: 620,
      y: 90,
      description: 'Declares deliver(), the operation every concrete vehicle must implement.',
    },
    {
      id: 'truck',
      label: 'Truck',
      role: 'Concrete Product',
      kind: 'class',
      x: 500,
      y: 230,
      description: 'Delivers cargo by road.',
    },
    {
      id: 'ship',
      label: 'Ship',
      role: 'Concrete Product',
      kind: 'class',
      x: 740,
      y: 230,
      description: 'Delivers cargo by sea.',
    },
    {
      id: 'logistics',
      label: 'Logistics',
      role: 'Creator (abstract)',
      kind: 'abstract',
      x: 260,
      y: 90,
      width: 180,
      description: 'Declares the abstract createTransport() factory method and a shared planDelivery() that uses it, without knowing which Transport it gets back.',
    },
    {
      id: 'roadLogistics',
      label: 'RoadLogistics',
      role: 'Concrete Creator',
      kind: 'class',
      x: 120,
      y: 230,
      description: 'Overrides createTransport() to return a new Truck.',
    },
    {
      id: 'seaLogistics',
      label: 'SeaLogistics',
      role: 'Concrete Creator',
      kind: 'class',
      x: 340,
      y: 340,
      description: 'Overrides createTransport() to return a new Ship.',
    },
    {
      id: 'client',
      label: 'Client',
      role: 'Client',
      kind: 'client',
      x: 120,
      y: 400,
      description: 'Works only against the abstract Logistics type — it calls planDelivery() without knowing or caring which Transport subclass is used underneath.',
    },
  ],
  relations: [
    { id: 'road-extends', from: 'roadLogistics', to: 'logistics', type: 'implements', description: 'RoadLogistics extends Logistics and overrides createTransport().' },
    { id: 'sea-extends', from: 'seaLogistics', to: 'logistics', type: 'implements', description: 'SeaLogistics extends Logistics and overrides createTransport().' },
    { id: 'truck-impl', from: 'truck', to: 'transport', type: 'implements', description: 'Truck implements the Transport interface.' },
    { id: 'ship-impl', from: 'ship', to: 'transport', type: 'implements', description: 'Ship implements the Transport interface.' },
    {
      id: 'road-creates',
      from: 'roadLogistics',
      to: 'truck',
      type: 'creates',
      label: 'createTransport()',
      description: 'RoadLogistics.createTransport() returns a new Truck.',
      code: 'roadLogistics',
    },
    {
      id: 'sea-creates',
      from: 'seaLogistics',
      to: 'ship',
      type: 'creates',
      label: 'createTransport()',
      description: 'SeaLogistics.createTransport() returns a new Ship.',
      code: 'seaLogistics',
    },
    {
      id: 'client-calls',
      from: 'client',
      to: 'logistics',
      type: 'calls',
      label: 'planDelivery()',
      description: 'The client only ever calls planDelivery() on whichever Logistics subclass it was given.',
      bend: -40,
      code: 'usage',
    },
    {
      id: 'logistics-delivers',
      from: 'logistics',
      to: 'transport',
      type: 'calls',
      label: 'deliver()',
      description: 'planDelivery() calls deliver() on the Transport it got back from createTransport(), through the interface only.',
      code: 'logistics',
    },
  ],
  steps: [
    {
      title: 'Shared algorithm, abstract step',
      description: 'Logistics.planDelivery() is fully implemented and shared by every subclass — except for one step, createTransport(), which is left abstract.',
      highlight: ['logistics'],
      code: 'logistics',
    },
    {
      title: 'Client picks a concrete creator',
      description: 'The client instantiates a RoadLogistics and calls planDelivery() on it, through the abstract Logistics type.',
      highlight: ['client', 'client-calls'],
      packets: [{ relation: 'client-calls', label: 'planDelivery()' }],
      code: 'usage',
    },
    {
      title: 'Factory method runs',
      description: 'Inside planDelivery(), the call to this.createTransport() resolves to RoadLogistics’s override, which builds a Truck.',
      highlight: ['roadLogistics', 'road-creates', 'truck'],
      packets: [{ relation: 'road-creates', label: 'new Truck()' }],
      notes: { truck: 'created' },
      code: 'roadLogistics',
    },
    {
      title: 'Deliver, polymorphically',
      description: 'planDelivery() calls deliver() on the Transport it got back, without ever knowing it is a Truck.',
      highlight: ['logistics', 'transport', 'truck', 'logistics-delivers'],
      packets: [{ relation: 'logistics-delivers', label: 'deliver()' }],
      notes: { truck: 'deliver() ran' },
      code: 'logistics',
    },
    {
      title: 'Swap the creator, not the algorithm',
      description: 'Using SeaLogistics instead produces a Ship and sails it — planDelivery() itself never changes.',
      highlight: ['seaLogistics', 'sea-creates', 'ship'],
      packets: [{ relation: 'sea-creates', label: 'new Ship()' }],
      notes: { ship: 'created' },
      code: 'seaLogistics',
    },
  ],
  code: tsExample,
  csharp: csExample,
  python: pyExample,
  go: goExample,
}
