import type { PatternDefinition } from '@/types/pattern'
import tsExample from './example.ts?raw'
import csExample from './example.cs?raw'
import pyExample from './example.py?raw'

export const pattern: PatternDefinition = {
  slug: 'plugin',
  name: 'Plugin',
  category: 'enterprise',
  order: 8,
  summary: 'Link implementations in at configuration or start-up time, not compile time, so adding one needs no change to the host.',
  intent:
    'Link implementations at configuration or start-up time rather than compile time (Fowler, Patterns of Enterprise Application Architecture). The host only ever depends on an interface and a registry; concrete plugins are discovered and registered without the host changing.',
  problem:
    'A host that calls concrete implementations directly has to be edited, recompiled and redeployed every time a new implementation shows up — a new export format, a new payment provider, a new notification channel. The host and every implementation end up compiled together, so adding one more case means touching code that otherwise has nothing to do with it, and a big if/switch keyed on type grows forever.',
  solution:
    'Define a narrow interface the host depends on, and a registry that looks plugins up by id. A loader reads a manifest — a plain list of plugin ids and the factories that build them — and registers one instance per entry before the host runs. The host only ever calls registry.get(id); it never names a concrete plugin class, so adding one is purely a manifest change.',
  analogy:
    'A power strip: it only knows the shape of a plug, not which appliance is attached. Adding a lamp or a charger never means rewiring the strip — you plug it in, and it works because both sides agreed on the socket shape ahead of time.',
  whenToUse: [
    'Third parties, or other teams, need to add behavior without touching or recompiling the host.',
    'The set of implementations is open-ended or configured per deployment (which exporters, which payment providers, which checks run).',
    'You want new capabilities to ship as an added file or package, not an edited one.',
    'A growing if/switch over a "type" field is the only thing standing between the host and a new case.',
  ],
  pros: [
    'New behavior ships by adding a plugin and a manifest entry — the host and registry are never edited.',
    'Keeps the host small: it depends on one interface and one registry, never on concrete implementations.',
    'Plugins can be developed, tested and even distributed independently of the host.',
    'The manifest is a single, explicit place that lists everything currently wired in.',
  ],
  cons: [
    'Indirection: tracing "what actually runs for id X" means following the manifest and the factory map, not just reading the host.',
    'An id that is misspelled, or missing from the manifest, only fails at the point something asks the registry for it.',
    'Real discovery mechanisms (classpath/assembly scanning, bundler globs) can make plugins "just appear", which is convenient but easy to lose track of.',
  ],
  realWorld: [
    'VS Code extensions, discovered and activated from a manifest without the editor knowing about any of them at compile time',
    'Vite and webpack plugins, each one a plain object implementing a known interface and listed in a config array',
    'Python packaging\'s entry_points, which let an installed package register itself under a group a host scans for',
    'Eclipse OSGi bundles, discovered and wired together at start-up',
    'This site: src/patterns/registry.ts and src/architectures/registry.ts auto-discover every pattern and architecture folder with import.meta.glob — CLAUDE.md says "Never hand-register a pattern".',
  ],
  related: ['strategy', 'abstract-factory', 'factory-method', 'dependency-injection'],

  // Diagram (viewBox 800 × 460, x/y are box centres)
  participants: [
    {
      id: 'host',
      label: 'Host',
      role: 'Client',
      kind: 'client',
      x: 110,
      y: 250,
      width: 150,
      description: 'A document exporter host. It depends on PluginRegistry and the Exporter interface only, and never names a concrete exporter class.',
    },
    {
      id: 'manifest',
      label: 'Manifest',
      role: 'Configuration data',
      kind: 'object',
      x: 250,
      y: 80,
      width: 150,
      description: 'A plain list of plugin ids and the factory each one maps to. Editing this list is the entire story for adding or removing a plugin.',
    },
    {
      id: 'pluginLoader',
      label: 'PluginLoader',
      role: 'Loader',
      kind: 'class',
      x: 440,
      y: 80,
      width: 160,
      description: 'Reads the manifest, looks each module name up in a map of known factories, and registers the resulting exporter with the registry.',
    },
    {
      id: 'pluginRegistry',
      label: 'PluginRegistry',
      role: 'Registry',
      kind: 'class',
      x: 650,
      y: 250,
      width: 180,
      description: 'Holds exporters in a map keyed by id. get(id) returns the matching plugin or throws a clear error listing which ids are actually registered.',
    },
    {
      id: 'exporter',
      label: 'Exporter',
      role: 'Plugin interface',
      kind: 'interface',
      x: 440,
      y: 390,
      width: 180,
      description: 'The only contract the host and the registry know about: an id and an export(doc) method. Every plugin implements exactly this.',
    },
    {
      id: 'markdownExporter',
      label: 'MarkdownExporter',
      role: 'Concrete Plugin',
      kind: 'class',
      x: 650,
      y: 390,
      width: 180,
      description: 'Renders a document as Markdown. Registered under the id "markdown".',
    },
    {
      id: 'htmlExporter',
      label: 'HtmlExporter',
      role: 'Concrete Plugin',
      kind: 'class',
      x: 230,
      y: 390,
      width: 180,
      description: 'Renders a document as HTML. Registered under the id "html".',
    },
  ],
  relations: [
    {
      id: 'loaderReadsManifest',
      from: 'pluginLoader',
      to: 'manifest',
      type: 'calls',
      label: 'read manifest',
      description: 'The loader reads the manifest before anything is registered — a plain list of {id, module} entries, not code.',
      code: 'pluginLoader',
    },
    {
      id: 'loaderRegisters',
      from: 'pluginLoader',
      to: 'pluginRegistry',
      type: 'calls',
      label: 'register(exporter)',
      description: 'For each manifest entry, the loader builds the plugin from the factory map and registers it under its id.',
      bend: 20,
      code: 'pluginLoader',
    },
    {
      id: 'markdownImpl',
      from: 'markdownExporter',
      to: 'exporter',
      type: 'implements',
      description: 'MarkdownExporter implements Exporter, so the registry and host can hold and call it through the interface alone.',
      code: 'markdownExporter',
    },
    {
      id: 'htmlImpl',
      from: 'htmlExporter',
      to: 'exporter',
      type: 'implements',
      description: 'HtmlExporter implements the same Exporter interface — the host cannot tell the two apart except by id.',
      code: 'htmlExporter',
    },
    {
      id: 'registryHolds',
      from: 'pluginRegistry',
      to: 'exporter',
      type: 'holds',
      label: 'map: id → Exporter',
      description: 'The registry keeps every registered plugin in a map keyed by id, typed only as Exporter.',
      code: 'pluginRegistry',
    },
    {
      id: 'hostGet',
      from: 'host',
      to: 'pluginRegistry',
      type: 'calls',
      label: 'get(id)',
      description: 'The host asks the registry for a plugin by id. It never constructs or names a concrete exporter class.',
      bend: -15,
      code: 'host',
    },
    {
      id: 'hostExport',
      from: 'host',
      to: 'exporter',
      type: 'calls',
      label: 'export(doc)',
      description: 'Once the host has a plugin back from the registry, it calls export() on it through the Exporter interface.',
      code: 'host',
    },
  ],

  // Animated scenario
  steps: [
    {
      title: 'Host starts with an empty registry',
      description: 'Before anything loads, PluginRegistry holds no exporters at all. The host cannot do anything useful yet.',
      highlight: ['host', 'pluginRegistry'],
      notes: { pluginRegistry: 'registered: (none)' },
      code: 'pluginRegistry',
    },
    {
      title: 'The loader reads the manifest',
      description: 'PluginLoader reads a plain list of {id, module} entries — two entries, for "markdown" and "html".',
      highlight: ['pluginLoader', 'manifest', 'loaderReadsManifest'],
      notes: { manifest: 'markdown, html' },
      code: 'manifest',
    },
    {
      title: 'The loader registers each plugin under its id',
      description: 'For every manifest entry, the loader builds the plugin from the factory map and registers it. MarkdownExporter and HtmlExporter both implement Exporter, so the registry can hold both the same way.',
      highlight: ['pluginLoader', 'pluginRegistry', 'loaderRegisters', 'markdownExporter', 'htmlExporter', 'markdownImpl', 'htmlImpl', 'registryHolds'],
      notes: { pluginRegistry: 'registered: markdown, html' },
      code: 'pluginLoader',
    },
    {
      title: 'The host asks for "html"',
      description: 'The host calls registry.get("html"). It never references HtmlExporter by name — only the id.',
      highlight: ['host', 'pluginRegistry', 'hostGet'],
      packets: [{ relation: 'hostGet', label: 'get("html")' }],
      notes: { host: 'needs the html exporter' },
      code: 'host',
    },
    {
      title: 'The registry returns the plugin, and the host calls export()',
      description: 'The registry hands back the HtmlExporter instance, typed as Exporter. The host calls export(doc) on it without knowing which concrete class it got.',
      highlight: ['pluginRegistry', 'host', 'hostGet', 'hostExport', 'exporter', 'htmlExporter'],
      packets: [
        { relation: 'hostGet', label: 'HtmlExporter', reverse: true },
        { relation: 'hostExport', label: 'export(doc)' },
      ],
      notes: { host: '<h1>Quarterly Report</h1><p>Revenue is up.</p>' },
      code: 'host',
    },
    {
      title: 'A new plugin is added to the manifest — the host is untouched',
      description: 'A third entry, {id: "json", module: "json-exporter"}, is appended to the manifest. PluginLoader and PluginRegistry run exactly the same code; Host and its export() method are not edited at all.',
      highlight: ['manifest', 'pluginLoader', 'pluginRegistry'],
      notes: { pluginRegistry: 'registered: markdown, html, json' },
      code: 'usage',
    },
    {
      title: 'An unknown id fails with a clear error',
      description: 'Asking the registry for "pdf" — a plugin that was never registered — throws an error that names the id and lists every id that actually is registered, so the mistake is obvious immediately.',
      highlight: ['host', 'pluginRegistry', 'hostGet'],
      notes: { pluginRegistry: 'no plugin registered for "pdf" (registered: markdown, html, json)' },
      code: 'usage',
    },
  ],

  // Regions: `// [id]` … `// [/id]`. A participant highlights the region with its own id by default.
  code: tsExample,
  csharp: csExample,
  python: pyExample,

  // Generic diagram is used — no custom Visualization.
}
